dist: trusty
language: java
jdk: oraclejdk8

before_install:
  - mvn -v
  - mvn -B -q clean install -DskipTests -f quickstart/pom.xml
  - mvn -B -q clean install -DskipTests -f http-methods/pom.xml
  - mvn -B -q clean install -DskipTests -f jaxrs-params/pom.xml
  - mvn -B -q clean install -DskipTests -f legacy/pom.xml
  - mvn -B -q clean install -DskipTests -f exception/pom.xml
  - mvn -B -q clean install -DskipTests -f async/pom.xml

script:
  - mvn clean verify -f quickstart/pom.xml
  - mvn clean verify -f http-methods/pom.xml
  - mvn clean verify -f jaxrs-params/pom.xml
  - mvn clean verify -f legacy/pom.xml
  - mvn clean verify -f exception/pom.xml
  - mvn clean verify -f async/pom.xml
